version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: smilentag/foodgram_backend:latest
    depends_on:
      - db
    env_file:
      - ./.env


volumes:
  data_value: