# Generated by Django 3.2.16 on 2023-03-20 08:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(10, 'Номер телефона должно содержать 10 символов.')], verbose_name='Телефон клиента')),
                ('tag', models.CharField(max_length=10, verbose_name='Тэг оператора')),
                ('code', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(3, 'Размер кода оператора должен быть 3 символа.'), django.core.validators.MaxValueValidator(3, 'Размер кода оператора должен быть 3 символа.')], verbose_name='Код оператора')),
                ('utc', models.IntegerField(validators=[django.core.validators.MinValueValidator(-12, 'Минимальный часовой пояс -12.'), django.core.validators.MaxValueValidator(14, 'Максимальный часовой пояс +14.')])),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('phone',),
            },
        ),
        migrations.CreateModel(
            name='CodeMobileOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10, verbose_name='Тэг оператора')),
                ('code', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(3, 'Размер кода оператора должен быть 3 символа.'), django.core.validators.MaxValueValidator(3, 'Размер кода оператора должен быть 3 символа.')], verbose_name='Код оператора')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start_mailing', models.DateTimeField(verbose_name='Дата и время начала отправки рассылки')),
                ('text', models.CharField(max_length=250, verbose_name='Сообщение')),
                ('datetime_stop_mailing', models.DateTimeField(verbose_name='Дата и время окончания отправки рассылки')),
                ('filter_property_mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='notification.codemobileoperator', verbose_name='Фильтр операторов')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('datetime_start_mailing',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(auto_now=True, verbose_name='Время отправки сообщения.')),
                ('status_send', models.BooleanField(default=False, verbose_name='Статус отправки сообщения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='notification.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='notification.mailing')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('datetime_create',),
            },
        ),
    ]
